name: CI/CD with Docker, Tests, Docker Hub, ECR, and EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: |
        cd realestateapi/realestateapi
        mvn -B clean package

    - name: Run Tests
      run: |
        cd realestateapi/realestateapi
        mvn test

    - name: Dockerize Application and Push to Docker Hub
      run: |
        cd realestateapi/realestateapi
        docker build -t ${{ secrets.DOCKER_USERNAME }}/realestateapi .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKER_USERNAME }}/realestateapi

  ecr-ec2-deployment:
    name: ECR and EC2 Deployment
    runs-on: ubuntu-latest
    needs: build-test-docker

    steps:
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
        aws configure set default.output json

    - name: Pull Docker Image from Docker Hub
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/realestateapi

    - name: Authenticate Docker to ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Tag Docker Image for ECR
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/realestateapi:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/realestateapi:latest

    - name: Push Docker Image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/realestateapi:latest

    - name: Create SSH directory and Write Private Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Debug SSH Command
      run: |
        echo ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_INSTANCE_PUBLIC_IP }} 'echo Hello'


    - name: Test SSH Connection
      run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_INSTANCE_PUBLIC_IP }} 'echo Connection Successful'


    # - name: SSH into EC2 and Deploy Docker Image
    #   run: |
    #     ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_INSTANCE_PUBLIC_IP }} 'docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/realestateapi:latest && docker run -d -p 8080:8080 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/realestateapi:latest'


